#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the alternatingCharacters function below.
def alternatingCharacters(s):
    deletions = 0
    index = 0    
    s = list(s)
    while index + 1 < len(s):
        if s[index] == s[index + 1]:
            s.pop(index)
            deletions += 1
        else:
            index +=1
    return deletions
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input())

    for q_itr in range(q):
        s = input()

        result = alternatingCharacters(s)

        fptr.write(str(result) + '\n')

    fptr.close()
