#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the makeAnagram function below.
def makeAnagram(a, b):

    anaDict = {}
    for i in range(len(a)):
        if a[i] not in anaDict: 
            anaDict[a[i]] = 1
        else:
            anaDict[a[i]] += 1
    
    for i in range(len(b)): # total differences will be != 0
        if b[i] not in anaDict:
            anaDict[b[i]] = -1
        else:
            anaDict[b[i]] -= 1
    
    return (sum(map(abs,anaDict.values()))) # by getting the abs of all values we can see the total dif

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    a = input()

    b = input()

    res = makeAnagram(a, b)

    fptr.write(str(res) + '\n')

    fptr.close()
