#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the candies function below.
def candies(n, arr):
    if len(arr)==1: # base case
        return 1
    
    candy = [1]*len(arr)
    for i in range(1,len(arr)): # get candies to give looking L --> R
        if arr[i]> arr[i-1]:
            candy[i]=candy[i-1]+1
            
    for i in range(len(arr)-2,-1,-1): # get candies to give looking L <-- R
        if arr[i]> arr[i+1]:
            candy[i]=max(candy[i],candy[i+1]+1)

    return sum(candy)
        
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    arr = []

    for _ in range(n):
        arr_item = int(input())
        arr.append(arr_item)

    result = candies(n, arr)

    fptr.write(str(result) + '\n')

    fptr.close()
