#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the freqQuery function below.
def freqQuery(queries):
    queryDict = {}
    arr = []
    for i in range(len(queries)):
        if queries[i][0] == 1:
            if queries[i][1] not in queryDict:  # add new entry into dictionary
                queryDict[queries[i][1]] = 1
            else:
                queryDict[queries[i][1]] += 1
                
        elif queries[i][0] == 2:
            if queries[i][1] in queryDict and queryDict[queries[i][1]] > 0: # if key exists reduce
                queryDict[queries[i][1]] -= 1
                if queryDict[queries[i][1]] == 0: # if value is at zero remove key
                    del queryDict[queries[i][1]]
                    
        elif queries[i][0] == 3:
            if queries[i][1] in set(queryDict.values()):  # if value in dictionary return 1
                arr.append(1)
            else:
                arr.append(0)
    return arr
                
    print(queryDict)
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    queries = []

    for _ in range(q):
        queries.append(list(map(int, input().rstrip().split())))

    ans = freqQuery(queries)

    fptr.write('\n'.join(map(str, ans)))
    fptr.write('\n')

    fptr.close()
