#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the twoStrings function below.
def twoStrings(s1, s2):
    charDict = {}
    for i in range(len(s1)):    # add each unique char to Dictionary
        if s1[i] not in charDict:
            charDict[s1[i]] = True
            
    for i in range(len(s2)):    #if char from s2 in dict return true
        if s2[i] in charDict:
            return "YES"
    return "NO"

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input())

    for q_itr in range(q):
        s1 = input()

        s2 = input()

        result = twoStrings(s1, s2)

        fptr.write(result + '\n')

    fptr.close()
