#!/bin/python3

import sys
from math import ceil
def lowestTriangle(base, area):
    # Complete this function
    return ceil((area * 2)/ base)

base, area = input().strip().split(' ')
base, area = [int(base), int(area)]
height = lowestTriangle(base, area)
print(height)
