#!/bin/python3

import os
import sys

#
# Complete the restaurant function below.
#
def restaurant(l, b):
    if(l==b):
        return 1
    else:
        index = min(l,b)
        for i in range(1,index+1):
            if(l%i==0 and b%i==0):
                val1 = l//i
                val2 = b//i
                final = val1 * val2
        return final

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        lb = input().split()

        l = int(lb[0])

        b = int(lb[1])

        result = restaurant(l, b)

        fptr.write(str(result) + '\n')

    fptr.close()
