#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the beautifulPairs function below.
def beautifulPairs(A, B):
    pairDict = {}
    totalPairs = 0
    for i in range(len(A)):
        if A[i] not in pairDict:
            pairDict[A[i]] = 1
        else:
           pairDict[A[i]] += 1 
    for i in range(len(B)):
        if B[i] in pairDict:
            pairDict[B[i]] -= 1 
            totalPairs += 1
            if pairDict[B[i]] == 0:
                del pairDict[B[i]]
    if pairDict:
        return totalPairs + 1
    else:
        return totalPairs - 1
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    A = list(map(int, input().rstrip().split()))

    B = list(map(int, input().rstrip().split()))

    result = beautifulPairs(A, B)

    fptr.write(str(result) + '\n')

    fptr.close()
