#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the jimOrders function below.
def jimOrders(orders):
    timeNeeded = []
    for i, val in enumerate(orders):
        timeNeeded.append([val[0]+val[1],i+1])

    timeNeeded.sort()
    
    order = []
    for i in timeNeeded:
        order.append(i[1])
        
    return order
        
    
        
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    orders = []

    for _ in range(n):
        orders.append(list(map(int, input().rstrip().split())))

    result = jimOrders(orders)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
