#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the toys function below.
def toys(w):
    boxesNeeded = 1
    w.sort()
    boxLimit = w[0] + 4
    for i in range(len(w)):
        if w[i]>boxLimit:
            boxesNeeded += 1
            boxLimit = w[i] + 4
    return boxesNeeded
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    w = list(map(int, input().rstrip().split()))

    result = toys(w)

    fptr.write(str(result) + '\n')

    fptr.close()
