#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the whatFlavors function below.
def whatFlavors(cost, money):
    #key is price, val is index + 1
    costDict = {}
    
    for i in range(len(cost)):
        
        if money - cost[i] in costDict: # if difference is already in dictionary
            print("{} {}".format(costDict[money - cost[i]], i + 1))
            break
        if cost[i] not in costDict: # adds the first instance of price to dictionary
            costDict[cost[i]] = i + 1
        
    
if __name__ == '__main__':
    t = int(input())

    for t_itr in range(t):
        money = int(input())

        n = int(input())

        cost = list(map(int, input().rstrip().split()))

        whatFlavors(cost, money)
