#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the countSwaps function below.
def countSwaps(a):
    numSwaps = 0
    length = len(a)
    
    for i in range(length):
        for j in range(length - 1):
            if a[j]> a[j + 1]:  # swap
                temp = a[j]
                a[j] = a[j + 1]
                a[j + 1] = temp
                numSwaps += 1
    
    print("Array is sorted in {} swaps.".format(numSwaps))    
    print("First Element: {}".format(a[0]))
    print("Last Element: {}".format(a[-1]))
    
if __name__ == '__main__':
    n = int(input())

    a = list(map(int, input().rstrip().split()))

    countSwaps(a)
