#!/bin/python3

import math
import os
import random
import re
import sys
import math

# Complete the squares function below.
def squares(a, b):
    minSquare = 0 # brute force
    validSquares = 0
        
    while(minSquare**2<a):
        minSquare+=1
    
    while(minSquare**2<=b):
        minSquare+=1
        validSquares+=1
        
    return(validSquares)
    
    
'''
    return math.floor(math.sqrt(b)) - math.ceil(math.sqrt(a)) + 1   #optimized
'''
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input())

    for q_itr in range(q):
        ab = input().split()

        a = int(ab[0])

        b = int(ab[1])

        result = squares(a, b)

        fptr.write(str(result) + '\n')

    fptr.close()
