#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the strangeCounter function below.
def strangeCounter(t):
    val = 3
    rangeLow = 1
    rangeHigh = 3
    
    while(t > rangeHigh):
        rangeLow += val
        val = val * 2
        rangeHigh = rangeLow + val - 1
    return(val - (t - rangeLow))
    
    
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    result = strangeCounter(t)

    fptr.write(str(result) + '\n')

    fptr.close()
