#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the maxSubarray function below.
def maxSubarray(arr):
    curMax, globalMax, arrSum = arr[0], arr[0], arr[0]
    
    for i in range(1, len(arr)):
        arrSum = max(arrSum, arr[i], arrSum + arr[i])
        curMax = max(arr[i], curMax + arr[i])
        globalMax = max(curMax, globalMax)
        

    
    return(globalMax, arrSum)
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        n = int(input())

        arr = list(map(int, input().rstrip().split()))

        result = maxSubarray(arr)

        fptr.write(' '.join(map(str, result)))
        fptr.write('\n')

    fptr.close()
