#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the luckBalance function below.
def luckBalance(k, contests):
    luck = 0
    contests.sort(reverse = True) # sort array from largest to smallest
    for i in range(len(contests)):
        if contests[i][1] == 0: #all unimportant matches get added
            luck += contests[i][0]
        elif k > 0: # gain points on the k most important matches
            k -= 1
            luck += contests[i][0]
        else: #lose points on the remaining
            luck -= contests[i][0]
    return luck
                
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nk = input().split()

    n = int(nk[0])

    k = int(nk[1])

    contests = []

    for _ in range(n):
        contests.append(list(map(int, input().rstrip().split())))

    result = luckBalance(k, contests)

    fptr.write(str(result) + '\n')

    fptr.close()
